logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.SQL: warn
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: ${JDBC_DATABASE_PASSWORD:}
    url: ${JDBC_DATABASE_URL:}
    username: ${JDBC_DATABASE_USERNAME:}
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    defer-datasource-initialization: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    cache: false

cloudinary:
  api-key: 838182148315422
  api-secret: ${CLOUDINARY_API_SECRET}
  cloud-name: dit8nlten

schedulers:
  cron: "0 0 09 * * ?"
  cron2: "* */20 * ? * *"

server.port: ${PORT:8080}